// @ts-nocheck
// GENERATED by tauri-specta. Do not edit by hand.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Force a panic, to exercise the panic hook, backtrace capture, log flush and the
 * crash screen.
 */
async debugPanic() : Promise<void> {
    await TAURI_INVOKE("debug_panic");
},
/**
 * Force an `AppError`, to exercise construction-time logging, the Recent problems
 * ring and the correlation id reaching the UI.
 */
async debugError() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_error") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appInfo() : Promise<AppInfo> {
    return await TAURI_INVOKE("app_info");
},
/**
 * The last ten failures, for Settings → Advanced → Recent problems.
 * 
 * Errors that are logged but never surfaced are never reported, and the audience
 * here is developers: showing them the actual errors raises report quality more than
 * any amount of instructions.
 */
async recentProblems() : Promise<ProblemRecord[]> {
    return await TAURI_INVOKE("recent_problems");
},
async openKnownFolder(folder: KnownFolder) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_known_folder", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Copy summary** — the low-friction default. Returns the markdown; the webview
 * puts it on the clipboard.
 */
async diagnosticsSummary(client: ClientEnvironment, subject: ReportSubject) : Promise<string> {
    return await TAURI_INVOKE("diagnostics_summary", { client, subject });
},
/**
 * Build the bundle and describe it **without writing anything**.
 */
async diagnosticsPreview(client: ClientEnvironment, subject: ReportSubject) : Promise<BundlePreview> {
    return await TAURI_INVOKE("diagnostics_preview", { client, subject });
},
/**
 * Write the bundle the user has just previewed.
 * 
 * Rebuilt rather than carried over from the preview call: a few hundred milliseconds
 * of log lines may have been written in between, and the manifest states the sizes of
 * what is actually in the zip.
 */
async diagnosticsExport(path: string, client: ClientEnvironment, subject: ReportSubject) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("diagnostics_export", { path, client, subject }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The name the save dialog should suggest.
 */
async diagnosticsSuggestedName() : Promise<string> {
    return await TAURI_INVOKE("diagnostics_suggested_name");
},
/**
 * The wgm Release check. The only outbound request in the product, and it happens
 * only because the user clicked.
 */
async checkForRelease() : Promise<Result<ReleaseCheck, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_release") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Report where the maximise button ended up, so `WM_NCHITTEST` can answer
 * `HTMAXBUTTON` over it and Snap Layouts still appears.
 */
async setMaximizeButtonRect(rect: ButtonRect) : Promise<void> {
    await TAURI_INVOKE("set_maximize_button_rect", { rect });
},
/**
 * `Alt+Space`. Undecorated windows lose the system menu by default, and it is how
 * screen reader users have always reached window commands.
 */
async openSystemMenu() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_system_menu") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show the window.
 * 
 * Called on first paint, and by a 3-second failsafe in the frontend. Either alone is
 * insufficient: the failsafe without the static fallback markup reveals a blank white
 * window, which is the worst failure in the app.
 */
async showWindow() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsGet() : Promise<Settings> {
    return await TAURI_INVOKE("settings_get");
},
async settingsStatus() : Promise<DocumentStatus> {
    return await TAURI_INVOKE("settings_status");
},
/**
 * Replace the whole Settings object.
 * 
 * One command rather than one per field: the schema is validated as a whole, and a
 * per-field command surface would be a second place for the shape to drift.
 */
async settingsSet(settings: Settings) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsSetColorScheme(value: ColorSchemePreference) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set_color_scheme", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsSetAccent(value: Accent) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set_accent", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsSetDensity(value: Density) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set_density", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsSetReduceMotion(value: ReduceMotion) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set_reduce_motion", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsSetLogLevel(value: LogLevel) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set_log_level", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsSetLogRetentionDays(value: number) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set_log_retention_days", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsSetRestoreWindowPosition(value: boolean) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set_restore_window_position", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsSetConfirmDestructiveActions(value: boolean) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set_confirm_destructive_actions", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async settingsSetReleaseCheckEnabled(value: boolean) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set_release_check_enabled", { value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset to defaults. The one action gated by confirm-before-destructive-actions,
 * which is enforced in the UI — this command does what it is told.
 */
async settingsReset() : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_reset") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The JSON an export writes. Rust produces the bytes; the webview never touches a
 * file, only a path from the native picker.
 */
async settingsExport(path: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_export", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Everything an export envelope carries, for a UI that wants to show it.
 */
async settingsExportPreview() : Promise<SettingsExport> {
    return await TAURI_INVOKE("settings_export_preview");
},
/**
 * Read and validate an import file **without applying it**.
 * 
 * The preview is the point: an older schema is migrated and then shown as
 * *"this will change 4 settings"* before anything happens.
 */
async settingsImportPreview(path: string) : Promise<Result<ImportPreview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_import_preview", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply an import.
 * 
 * **The backup is written first and the import aborts if it cannot be.** The backup
 * is the undo; without it the import is not safe to perform.
 */
async settingsImportApply(path: string) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_import_apply", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceGet() : Promise<WorkspaceState> {
    return await TAURI_INVOKE("workspace_get");
},
async workspaceStatus() : Promise<DocumentStatus> {
    return await TAURI_INVOKE("workspace_status");
},
/**
 * Persist the Sidebar width.
 * 
 * The frontend debounces this by 300 ms during a drag: the width updates live on
 * screen and the file is written once the user stops, rather than sixty times a
 * second through a single global write lock.
 */
async workspaceSetSidebarWidth(width: number) : Promise<Result<WorkspaceState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_set_sidebar_width", { width }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the Rail state.
 * 
 * Only a deliberate collapse is recorded. A Sidebar forced to the Rail because the
 * window is under 900px wide is **not** written here — a narrow window must not
 * permanently collapse the Sidebar.
 */
async workspaceSetSidebarCollapsed(collapsed: boolean) : Promise<Result<WorkspaceState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_set_sidebar_collapsed", { collapsed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record that setup finished, against the version that ran it.
 * 
 * A version string rather than a boolean, so a future major release can replay a
 * single "what's new" step without replaying the whole thing.
 */
async workspaceCompleteOnboarding() : Promise<Result<WorkspaceState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_complete_onboarding") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * *Show setup again*, from Settings → About.
 */
async workspaceReplayOnboarding() : Promise<Result<WorkspaceState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_replay_onboarding") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * The single user-selected hue driving primary buttons and interactive emphasis.
 * 
 * Eight fixed, contrast-verified choices rather than a picker: a freeform hue would
 * let a user choose one that fails WCAG AA and there would be no way to stop them.
 */
export type Accent = "blue" | "violet" | "cyan" | "emerald" | "amber" | "orange" | "rose" | "neutral"
export type Advanced = { logLevel: LogLevel; 
/**
 * Days. Clamped to `LOG_RETENTION_RANGE`; a size cap applies as well, because a
 * Trace-level session can outgrow any day-based window in hours.
 */
logRetentionDays: number }
/**
 * The error every command returns. See the module docs for the two rules it obeys.
 */
export type AppError = { code: ErrorCode; 
/**
 * Structured, translatable interpolation parameters — `{ "path": "..." }`.
 * Values are already redacted where they name a filesystem location.
 */
context: Partial<{ [key in string]: string }>; 
/**
 * Whether the user can do something other than restart.
 */
recoverable: boolean; 
/**
 * Shared with the log lines that produced this failure, so a user quoting
 * `a3f9c1` can be found in a Diagnostics Bundle. Displayed, not just logged.
 */
correlationId: string }
/**
 * Everything Settings → About displays, in one round trip.
 */
export type AppInfo = { version: string; commit: string; buildDate: string; tauriVersion: string; sessionId: string; 
/**
 * Already redacted: About is a screen people screenshot.
 */
dataDir: string; logDir: string; storageMode: StorageMode; pathNotes: PathNote[]; ephemeral: boolean }
/**
 * Color Scheme, Accent and density together. `CONTEXT.md` calls this Appearance and
 * deliberately not "Theme", which has meant all three at different times.
 */
export type Appearance = { colorScheme: ColorSchemePreference; accent: Accent; density: Density; reduceMotion: ReduceMotion }
/**
 * One file, as the preview dialog shows it.
 */
export type BundleFile = { name: string; 
/**
 * u32 rather than usize: specta refuses to emit a BigInt into the bindings, and
 * a bundle file larger than 4 GB is not a case worth typing for.
 */
bytes: number; truncated: boolean; 
/**
 * The whole file when it is small enough to read, so the user can actually check
 * the redaction rather than take it on trust. `None` for the large log files.
 */
preview: string | null }
/**
 * What [`build`] produces: everything the zip will contain, before it exists.
 */
export type BundlePreview = { files: BundleFile[]; totalBytes: number; 
/**
 * The name the zip would be saved under.
 */
suggestedName: string; 
/**
 * False when the username could not be determined. The UI must refuse to save.
 */
redactionSafe: boolean; 
/**
 * Machine-readable notes about what was dropped or could not be read.
 */
notes: string[] }
/**
 * Where the maximise button is, in physical pixels relative to the window.
 * 
 * The frontend owns the layout, so the frontend reports this: Rust cannot know where
 * a React component ended up. `WM_NCHITTEST` reads it to decide when to answer
 * `HTMAXBUTTON`, which is what makes Snap Layouts appear on hover.
 */
export type ButtonRect = { x: number; y: number; width: number; height: number }
/**
 * Facts only the webview knows, passed in rather than guessed at.
 * 
 * Rendering and layout bugs are almost always specific to the WebView2 version or
 * the display scaling, so neither is padding.
 */
export type ClientEnvironment = { webviewVersion: string; displayScaling: string; locale: string; timezone: string; 
/**
 * The Color Scheme actually in effect, not the preference.
 */
colorScheme: string; highContrast: boolean; windowSize: string }
/**
 * Which of Light, Dark or Darker is in effect.
 * 
 * `System` is a *preference*, not a scheme: it resolves to Light or Dark and never
 * to Darker, because the operating system has no signal for "extra dark".
 */
export type ColorSchemePreference = "system" | "light" | "dark" | "darker"
/**
 * Density changes spacing, never type size.
 */
export type Density = "comfortable" | "compact"
/**
 * What the UI needs to know about a document's health, without knowing its shape.
 */
export type DocumentStatus = { outcome: LoadOutcome; 
/**
 * True while this document cannot be persisted — Ephemeral Mode.
 */
ephemeral: boolean; 
/**
 * Consecutive failed writes. **Coalesced into one banner, not one toast per
 * toggle**: instant apply means every switch writes, and a file locked by an
 * antivirus scanner would otherwise produce a wall of toasts.
 */
consecutiveWriteFailures: number; 
/**
 * Fields the file carried that this build does not know. Logged and ignored.
 */
unknownFields: string[]; 
/**
 * Values that were out of range and were pulled back in.
 */
clampedFields: string[] }
/**
 * Stable, machine-readable failure codes.
 * 
 * Serialised as `SCREAMING_SNAKE_CASE`, which is what appears in a log line, in a
 * Diagnostics Bundle and in `src/i18n/en.ts`. **Never rename a variant**: a user's
 * old log file and a maintainer's grep both depend on these strings outliving the
 * release that produced them.
 */
export type ErrorCode = 
/**
 * The data directory could not be resolved or created anywhere.
 */
"STORAGE_UNAVAILABLE" | 
/**
 * A document file exists but could not be read.
 */
"DOCUMENT_READ_FAILED" | 
/**
 * A document could not be written after the retry budget was spent.
 */
"DOCUMENT_WRITE_FAILED" | 
/**
 * A document's JSON could not be parsed. The original is backed up, never deleted.
 */
"DOCUMENT_CORRUPT" | 
/**
 * A document declares a `schemaVersion` this build does not know about.
 */
"DOCUMENT_SCHEMA_TOO_NEW" | 
/**
 * A migration returned an error or panicked. Treated exactly as corruption.
 */
"DOCUMENT_MIGRATION_FAILED" | 
/**
 * A write was attempted while running in Ephemeral Mode.
 */
"STORAGE_EPHEMERAL" | 
/**
 * An import file failed validation. Nothing was applied.
 */
"IMPORT_INVALID" | 
/**
 * An import file came from a newer schema than this build understands.
 */
"IMPORT_SCHEMA_TOO_NEW" | 
/**
 * The pre-import backup could not be written, so the import was aborted.
 */
"IMPORT_BACKUP_FAILED" | 
/**
 * An export target could not be written.
 */
"EXPORT_FAILED" | 
/**
 * The Diagnostics Bundle could not be assembled or written.
 */
"DIAGNOSTICS_BUNDLE_FAILED" | 
/**
 * Redaction could not determine the current username, so nothing was written.
 */
"DIAGNOSTICS_REDACTION_UNSAFE" | "RELEASE_CHECK_OFFLINE" | "RELEASE_CHECK_SERVER_ERROR" | "RELEASE_CHECK_RATE_LIMITED" | "RELEASE_CHECK_TIMEOUT" | "RELEASE_CHECK_MALFORMED" | 
/**
 * A Windows API call the UI depends on failed.
 */
"WINDOW_OPERATION_FAILED" | 
/**
 * Anything that did not arrive in our shape: a transport failure, a
 * serialisation error, or a panic crossing the boundary. A raw string reaching
 * the UI would mean no translation, no correlation id and no recovery action.
 */
"IPC_UNKNOWN" | 
/**
 * Produced only by the dev-only `debug_error` command.
 */
"DEBUG_FORCED"
export type General = { restoreWindowPosition: boolean; 
/**
 * The one exception to instant apply: this genuinely gates Reset to defaults,
 * which is why it is rendered at all. A control that does nothing is not shown.
 */
confirmDestructiveActions: boolean }
export type ImportChange = { path: string; current: string; incoming: string }
/**
 * What an import would do, shown to the user before anything is applied.
 */
export type ImportPreview = { 
/**
 * Dotted paths whose value differs from what is in effect now.
 */
changes: ImportChange[]; 
/**
 * True when the file came from an older schema and was migrated to preview it.
 */
migrated: boolean; fromVersion: number }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Open a folder in Explorer. Takes an enum rather than a path, so the webview cannot
 * name an arbitrary directory.
 */
export type KnownFolder = "data" | "logs"
/**
 * What happened when a document was loaded. Surfaced in the UI: a corrupt file
 * produces a persistent banner naming the backup, and a too-new file produces
 * Ephemeral Mode.
 */
export type LoadOutcome = 
/**
 * Read and parsed with nothing to report.
 */
{ kind: "loaded" } | 
/**
 * No file yet. First run, or the user deleted it.
 */
{ kind: "missing" } | 
/**
 * Fields were absent and filled from Defaults. The file is rewritten.
 */
{ kind: "filledFromDefaults"; fields: string[] } | 
/**
 * The migration chain ran. The file is rewritten at the new version.
 */
{ kind: "migrated"; from: number } | 
/**
 * Unparseable, or a migration failed. The original is copied aside and **never
 * deleted**; the copy's name is shown to the user.
 */
{ kind: "corrupt"; backup: string } | 
/**
 * Written by a newer build. wgm does not guess: it boots from Defaults in
 * Ephemeral Mode and does not overwrite the file.
 */
{ kind: "schemaTooNew"; found: number; expected: number } | 
/**
 * The file exists but could not be read at all.
 */
{ kind: "unreadable" }
export type LogLevel = "error" | "warn" | "info" | "debug" | "trace"
/**
 * Onboarding progress.
 */
export type Onboarding = { 
/**
 * The wgm version whose setup the user completed — **not a boolean**, so a
 * future major release can replay a single "what's new" step without replaying
 * the whole thing. `None` means setup has never been finished.
 */
completedVersion: string | null }
/**
 * A machine-readable note about how the location was resolved. No English: the
 * catalog in `src/i18n/en.ts` owns the sentence.
 */
export type PathNote = 
/**
 * A `wgm.portable` marker was found but its folder could not be written to.
 */
"PORTABLE_FOLDER_READ_ONLY" | 
/**
 * `%APPDATA%` could not be resolved from the environment.
 */
"APP_DATA_UNAVAILABLE" | 
/**
 * `%APPDATA%` resolved but could not be written to.
 */
"APP_DATA_READ_ONLY"
export type Privacy = { 
/**
 * Whether Settings → About offers the manual wgm Release check at all. The check
 * itself never runs on its own — see ADR-0003.
 */
releaseCheckEnabled: boolean }
/**
 * One failure, as Settings → Advanced shows it.
 */
export type ProblemRecord = { timestamp: string; code: ErrorCode; correlationId: string; context: Partial<{ [key in string]: string }> }
/**
 * Reduced motion is a tri-state, not a boolean, so the in-app setting can override
 * the OS **in both directions** rather than only tightening it.
 */
export type ReduceMotion = "system" | "on" | "off"
/**
 * Every outcome the UI has copy for, per `docs/failure-modes.md` §5.
 */
export type ReleaseCheck = 
/**
 * A newer release exists.
 */
{ status: "newer"; version: string; url: string } | 
/**
 * Already current.
 */
{ status: "upToDate"; version: string }
/**
 * What is being reported, when a report is about one specific failure.
 */
export type ReportSubject = { correlationId: string | null; errorCode: string | null }
/**
 * The validated, in-memory configuration object. Distinct from the file it came from.
 */
export type Settings = { schemaVersion: number; appearance: Appearance; general: General; advanced: Advanced; privacy: Privacy }
/**
 * The envelope an exported Settings file is wrapped in.
 * 
 * Carries enough for the importing build to decide what to do without guessing:
 * the schema version drives migration or refusal, and the other two fields are
 * there for a human reading the file.
 */
export type SettingsExport = { schemaVersion: number; exportedAt: string; appVersion: string; settings: JsonValue }
/**
 * The Sidebar and its collapsed form, the Rail. One component in two states, not two
 * components — so this is one field, not two.
 */
export type SidebarState = { width: number; 
/**
 * True when the user collapsed it to the Rail. Below a 900px window width the
 * Rail is forced regardless, and that is *not* recorded here — a narrow window
 * must not permanently collapse the Sidebar.
 */
collapsed: boolean }
export type StorageMode = "PORTABLE" | "APP_DATA" | 
/**
 * wgm cannot persist. Settings live in memory only and a banner says so. One
 * name for one state — never "read-only mode" or "safe mode".
 */
"EPHEMERAL"
export type WindowGeometry = { width: number; height: number; 
/**
 * Absent until the window has been moved, so a first run is centred by the OS.
 */
x: number | null; y: number | null; maximized: boolean }
export type WorkspaceState = { schemaVersion: number; window: WindowGeometry; sidebar: SidebarState; onboarding: Onboarding }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
