/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as OnboardingRouteImport } from "./routes/onboarding"
import { Route as AppInstalledRouteImport } from "./routes/_app/installed"
import { Route as AppSearchRouteImport } from "./routes/_app/search"
import { Route as AppSettingsRouteImport } from "./routes/_app/settings"
import { Route as AppUpdatesRouteImport } from "./routes/_app/updates"
import { Route as AppKitsIndexRouteImport } from "./routes/_app/kits.index"
import { Route as AppKitsKitIdRouteImport } from "./routes/_app/kits.$kitId"
import { Route as AppSettingsIndexRouteImport } from "./routes/_app/settings.index"
import { Route as AppSettingsAboutRouteImport } from "./routes/_app/settings.about"
import { Route as AppSettingsAdvancedRouteImport } from "./routes/_app/settings.advanced"
import { Route as AppSettingsAppearanceRouteImport } from "./routes/_app/settings.appearance"
import { Route as AppSettingsGeneralRouteImport } from "./routes/_app/settings.general"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const AppInstalledRoute = AppInstalledRouteImport.update({
  id: "/installed",
  path: "/installed",
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesRoute = AppUpdatesRouteImport.update({
  id: "/updates",
  path: "/updates",
  getParentRoute: () => AppRoute,
} as any)
const AppKitsIndexRoute = AppKitsIndexRouteImport.update({
  id: "/kits/",
  path: "/kits/",
  getParentRoute: () => AppRoute,
} as any)
const AppKitsKitIdRoute = AppKitsKitIdRouteImport.update({
  id: "/kits/$kitId",
  path: "/kits/$kitId",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAboutRoute = AppSettingsAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAdvancedRoute = AppSettingsAdvancedRouteImport.update({
  id: "/advanced",
  path: "/advanced",
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: "/general",
  path: "/general",
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRoute
  "/installed": typeof AppInstalledRoute
  "/search": typeof AppSearchRoute
  "/settings": typeof AppSettingsRouteWithChildren
  "/updates": typeof AppUpdatesRoute
  "/kits/$kitId": typeof AppKitsKitIdRoute
  "/settings/about": typeof AppSettingsAboutRoute
  "/settings/advanced": typeof AppSettingsAdvancedRoute
  "/settings/appearance": typeof AppSettingsAppearanceRoute
  "/settings/general": typeof AppSettingsGeneralRoute
  "/kits/": typeof AppKitsIndexRoute
  "/settings/": typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRoute
  "/installed": typeof AppInstalledRoute
  "/search": typeof AppSearchRoute
  "/updates": typeof AppUpdatesRoute
  "/kits/$kitId": typeof AppKitsKitIdRoute
  "/settings/about": typeof AppSettingsAboutRoute
  "/settings/advanced": typeof AppSettingsAdvancedRoute
  "/settings/appearance": typeof AppSettingsAppearanceRoute
  "/settings/general": typeof AppSettingsGeneralRoute
  "/kits": typeof AppKitsIndexRoute
  "/settings": typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_app": typeof AppRouteWithChildren
  "/onboarding": typeof OnboardingRoute
  "/_app/installed": typeof AppInstalledRoute
  "/_app/search": typeof AppSearchRoute
  "/_app/settings": typeof AppSettingsRouteWithChildren
  "/_app/updates": typeof AppUpdatesRoute
  "/_app/kits/$kitId": typeof AppKitsKitIdRoute
  "/_app/settings/about": typeof AppSettingsAboutRoute
  "/_app/settings/advanced": typeof AppSettingsAdvancedRoute
  "/_app/settings/appearance": typeof AppSettingsAppearanceRoute
  "/_app/settings/general": typeof AppSettingsGeneralRoute
  "/_app/kits/": typeof AppKitsIndexRoute
  "/_app/settings/": typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/onboarding"
    | "/installed"
    | "/search"
    | "/settings"
    | "/updates"
    | "/kits/$kitId"
    | "/settings/about"
    | "/settings/advanced"
    | "/settings/appearance"
    | "/settings/general"
    | "/kits/"
    | "/settings/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/onboarding"
    | "/installed"
    | "/search"
    | "/updates"
    | "/kits/$kitId"
    | "/settings/about"
    | "/settings/advanced"
    | "/settings/appearance"
    | "/settings/general"
    | "/kits"
    | "/settings"
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/onboarding"
    | "/_app/installed"
    | "/_app/search"
    | "/_app/settings"
    | "/_app/updates"
    | "/_app/kits/$kitId"
    | "/_app/settings/about"
    | "/_app/settings/advanced"
    | "/_app/settings/appearance"
    | "/_app/settings/general"
    | "/_app/kits/"
    | "/_app/settings/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/installed": {
      id: "/_app/installed"
      path: "/installed"
      fullPath: "/installed"
      preLoaderRoute: typeof AppInstalledRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/search": {
      id: "/_app/search"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings": {
      id: "/_app/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/updates": {
      id: "/_app/updates"
      path: "/updates"
      fullPath: "/updates"
      preLoaderRoute: typeof AppUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/kits/": {
      id: "/_app/kits/"
      path: "/kits"
      fullPath: "/kits/"
      preLoaderRoute: typeof AppKitsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/kits/$kitId": {
      id: "/_app/kits/$kitId"
      path: "/kits/$kitId"
      fullPath: "/kits/$kitId"
      preLoaderRoute: typeof AppKitsKitIdRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings/": {
      id: "/_app/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    "/_app/settings/about": {
      id: "/_app/settings/about"
      path: "/about"
      fullPath: "/settings/about"
      preLoaderRoute: typeof AppSettingsAboutRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    "/_app/settings/advanced": {
      id: "/_app/settings/advanced"
      path: "/advanced"
      fullPath: "/settings/advanced"
      preLoaderRoute: typeof AppSettingsAdvancedRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    "/_app/settings/appearance": {
      id: "/_app/settings/appearance"
      path: "/appearance"
      fullPath: "/settings/appearance"
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    "/_app/settings/general": {
      id: "/_app/settings/general"
      path: "/general"
      fullPath: "/settings/general"
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAboutRoute: typeof AppSettingsAboutRoute
  AppSettingsAdvancedRoute: typeof AppSettingsAdvancedRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAboutRoute: AppSettingsAboutRoute,
  AppSettingsAdvancedRoute: AppSettingsAdvancedRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppInstalledRoute: typeof AppInstalledRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppUpdatesRoute: typeof AppUpdatesRoute
  AppKitsKitIdRoute: typeof AppKitsKitIdRoute
  AppKitsIndexRoute: typeof AppKitsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInstalledRoute: AppInstalledRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppUpdatesRoute: AppUpdatesRoute,
  AppKitsKitIdRoute: AppKitsKitIdRoute,
  AppKitsIndexRoute: AppKitsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
